//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C4LDataG3ContrerasMontesinos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DB_PAAC4G3ContrerasMontesinos : DbContext
    {
        public DB_PAAC4G3ContrerasMontesinos()
            : base("name=DB_PAAC4G3ContrerasMontesinos")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblInventario> tblInventario { get; set; }
    
        public virtual int pa_eliminar(Nullable<int> codigo, Nullable<bool> eliminado)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(int));
    
            var eliminadoParameter = eliminado.HasValue ?
                new ObjectParameter("eliminado", eliminado) :
                new ObjectParameter("eliminado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_eliminar", codigoParameter, eliminadoParameter);
        }
    
        public virtual int pa_ingresar(Nullable<int> codigo, Nullable<System.DateTime> fecha, Nullable<int> seccion, string nombreArticulo, string estado, Nullable<bool> etiquetado, string realizadoPor, Nullable<bool> eliminado)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(int));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var seccionParameter = seccion.HasValue ?
                new ObjectParameter("seccion", seccion) :
                new ObjectParameter("seccion", typeof(int));
    
            var nombreArticuloParameter = nombreArticulo != null ?
                new ObjectParameter("nombreArticulo", nombreArticulo) :
                new ObjectParameter("nombreArticulo", typeof(string));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            var etiquetadoParameter = etiquetado.HasValue ?
                new ObjectParameter("etiquetado", etiquetado) :
                new ObjectParameter("etiquetado", typeof(bool));
    
            var realizadoPorParameter = realizadoPor != null ?
                new ObjectParameter("realizadoPor", realizadoPor) :
                new ObjectParameter("realizadoPor", typeof(string));
    
            var eliminadoParameter = eliminado.HasValue ?
                new ObjectParameter("eliminado", eliminado) :
                new ObjectParameter("eliminado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_ingresar", codigoParameter, fechaParameter, seccionParameter, nombreArticuloParameter, estadoParameter, etiquetadoParameter, realizadoPorParameter, eliminadoParameter);
        }
    
        public virtual int pa_modificar(Nullable<int> id, Nullable<int> codigo, Nullable<System.DateTime> fecha, Nullable<int> seccion, string nombreArticulo, string estado, Nullable<bool> etiquetado, string realizadoPor)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(int));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var seccionParameter = seccion.HasValue ?
                new ObjectParameter("seccion", seccion) :
                new ObjectParameter("seccion", typeof(int));
    
            var nombreArticuloParameter = nombreArticulo != null ?
                new ObjectParameter("nombreArticulo", nombreArticulo) :
                new ObjectParameter("nombreArticulo", typeof(string));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            var etiquetadoParameter = etiquetado.HasValue ?
                new ObjectParameter("etiquetado", etiquetado) :
                new ObjectParameter("etiquetado", typeof(bool));
    
            var realizadoPorParameter = realizadoPor != null ?
                new ObjectParameter("realizadoPor", realizadoPor) :
                new ObjectParameter("realizadoPor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_modificar", idParameter, codigoParameter, fechaParameter, seccionParameter, nombreArticuloParameter, estadoParameter, etiquetadoParameter, realizadoPorParameter);
        }
    
        public virtual ObjectResult<pa_mostrar_Result> pa_mostrar(Nullable<int> codigo)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_mostrar_Result>("pa_mostrar", codigoParameter);
        }
    }
}
